### ISSUE TITLE
include a top-level CSS module that exports everything

### ISSUE THREAD

**Issue by cdepillabout** [slamdata/purescript-css#14]
`purescript-css` is really nice!

It might be a little easier for the end user if there was a top-level `CSS` module that exported everything from the submodules.

Right now, we have to write code like this:

```purescript
import CSS.FontFace (fontFaceFamily)
import CSS.Render (render, renderedSheet)
import CSS.String (fromString)
import CSS.Stylesheet (CSS(), fontFace)

style :: CSS
style = do
    fontFace $ fontFaceFamily $ fromString "Lato"

addCSS = do
    let sheet = fromMaybe "" <<< renderedSheet $ render style
    addStyleSheet sheet

addStyleSheet = ...
```

But it might be nicer for the end user to be able to write code like this:

```purescript
import CSS (CSS(), fontFace, fontFaceFamily, fromString, render, renderedSheet)

style :: CSS
style = do
    fontFace $ fontFaceFamily $ fromString "Lato"

addCSS = do
    let sheet = fromMaybe "" <<< renderedSheet $ render style
    addStyleSheet sheet

addStyleSheet = ...
```

**Comment by garyb** [comment]
Yeah, agreed, it's rather annoying to use right now. I've been meaning to do this but just haven't gotten around to it. I'd probably not export the rendering functions from `CSS` though, as they're less "globally useful" than the rest of it, given Halogen may be rendering your CSS, etc.

**Comment by cdepillabout** [comment]
I submited a pull request to add this: https://github.com/slamdata/purescript-css/pull/15
