### ISSUE TITLE
zIndex seems to be missing

### ISSUE THREAD

**Issue by maackle** [slamdata/purescript-css#65]
I had to write my own:

```purescript
zIndex :: Int -> CSS
zIndex z =
  (prefixed $ fromString "z-index") (show z)
```

**Comment by safareli** [comment]
I think we should add it,  do you want to open a PR?

**Comment by maackle** [comment]
Done, see #66.

This is the only property I could find that takes a dimensionless value. I also noticed that `scale()` is missing from `transform` even though `translate()` and `rotate()` are present, perhaps for the same reason that it takes dimensionless numbers? Maybe others got overlooked for that same reason.

**Comment by safareli** [comment]
@garyb might know the answer

**Comment by vyorkin** [comment]
I'll open a separate issue to track the missing transforms, going to send a PR adding them soon
