### ISSUE TITLE
Add `FontStyle` enum

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-css#69]

**Comment by vyorkin** [comment]
I've found there is already existing `FontStyle` newtype here: https://github.com/slamdata/purescript-css/blob/9e78699ea728f519ec5b3e830aa2036823dd50a7/src/CSS/Font.purs#L67 + values. Do you want to change this?

**Comment by garyb** [comment]
Perhaps this was missing when I opened the issue, but I think generally it might be nice to have "real types" rather than newtypes-over-strings for values that have a known set of possibilities?

**Comment by vyorkin** [comment]
Something like
```purescript
data ObliqueValue = Oblique | ObliqueDeg (Angle Deg)
data FontStyle = Normal | Italic | Oblique ObliqueValue
```
?

**Comment by garyb** [comment]
Yeah, exactly 👍
