### ISSUE TITLE
Won't build with latest `purescript-colors` 4.3.0

### ISSUE THREAD

**Issue by metaleap** [slamdata/purescript-css#73]
using `purs` current `master` branch (prints `--version` as `0.11.6 dev build`), attempting to `pulp build` build a project with `purescript-css` (got version 3.3.0 from Pursuit) in the deps (and insisting on `purescript-colors` 4.3.0) results in:

    * Building project in /home/rox/c/ps/test-pscorefn-src
    Compiling CSS.String
    Compiling CSS.Property
    Compiling CSS.Selector
    Compiling CSS.Color
    Error 1 of 2:
    
      at bower_components/purescript-css/src/CSS/Selector.purs line 25, column 8 - line 25, column 54
      
        Cannot derive a type class instance for
                                        
          Data.Generic.Generic Predicate
                                        
        since instances of this type class are not derivable.
        
        
      See https://github.com/purescript/documentation/blob/master/errors/CannotDerive.md for more information,
      or to contribute content related to this error.
      
    Error 2 of 2:
    
      at bower_components/purescript-css/src/CSS/Property.purs line 20, column 8 - line 20, column 52
      
        Cannot derive a type class instance for
                                       
          Data.Generic.Generic Prefixed
                                       
        since instances of this type class are not derivable.

**Comment by garyb** [comment]
This is because current master doesn't allow deriving of the old `Generic` anymore rather than a dependency issue.

**Comment by metaleap** [comment]
Yeah I'm running into this quite a bit right now as I'm going through everything-on-Pursuit  =)

**Comment by vyorkin** [comment]
Just thinking... does it make sense if I try and make a PR to use the `generics-rep` instead of `generics`? should be a pretty trivial change

**Comment by garyb** [comment]
Sure, or we can probably remove generics entirely - the need for deep generics isn't present anymore, so unless anything in here is being implemented with generics I don't think the instances are all that useful.
