### ISSUE TITLE
(##) is infix for `child` instead of `with`

### ISSUE THREAD

**Issue by jqyu** [slamdata/purescript-css#75]
https://github.com/slamdata/purescript-css/blob/v3.4.0/src/CSS/Selector.purs#L85-L85

Looks like a copy/paste mistake. For reference, in Clay `(#)` is the infix version of `with` with the same signature:
http://hackage.haskell.org/package/clay-0.12.2/docs/src/Clay-Selector.html#with

**Comment by vyorkin** [comment]
Also, it would be great to be able to omit the parentheses in cases like this:
![image](https://user-images.githubusercontent.com/988849/42419229-e16f7f32-829f-11e8-8900-0cd642aaa58a.png)
